name: conda_cuda3

channels:
  - pytorch
  - conda-forge
  - defaults
  - rdkit
  - anaconda
dependencies:
  - cudatoolkit=10.1
  - pip=20.0
  - python=3.7
  - pytorch=1.5
  - torchvision=0.6
  - matplotlib=3.3.0
  - numpy=1.18
  - pandas=1.1.3
  - rdkit=2020.03
  - scikit-learn
  - openbabel=2.4.1
  - scipy
  - cairosvg
  - jupyter 
 
